/** Shared onboarding-interview question list — single source of truth. */
export const ONBOARDING_QUESTIONS = [
  { id:'origin_1', section:'Origin Story', label:'Tell us your story — how did you get into this trade and start your business?' },
  { id:'origin_2', section:'Origin Story', label:'What makes you most proud about your company?' },
  { id:'origin_3', section:'Origin Story', label:'Is there a family or personal story connected to the business?' },
  { id:'services_1', section:'Services', label:'Walk me through your core services — what do you do?' },
  { id:'services_2', section:'Services', label:'Which service is your bread and butter, and which do you want to grow?' },
  { id:'services_3', section:'Services', label:'Describe your process from the first call to job completion.' },
  { id:'diff_1', section:'Differentiation', label:'What makes you different from competitors — and what do customers say about you?' },
  { id:'diff_2', section:'Differentiation', label:'Who is your ideal customer?' },
  { id:'area_1', section:'Service Area', label:'What areas do you serve, and where do you get the most work?' },
  { id:'area_2', section:'Service Area', label:'Are there specific neighborhoods or cities you want to target for growth?' },
  { id:'voice_1', section:'Brand Voice', label:'How would you describe your company\'s personality and tone?' },
  { id:'voice_2', section:'Brand Voice', label:'Any words, phrases, or taglines you love — or want to avoid on the website?' },
  { id:'cred_1', section:'Credentials', label:'What licenses, certifications, and insurance do you carry?' },
  { id:'cred_2', section:'Credentials', label:'Any awards, recognitions, or things you want to highlight?' },
  { id:'goals_1', section:'Goals', label:'What are your top goals for the new website?' },
  { id:'goals_2', section:'Goals', label:'What does success look like 6 months from now?' },
  { id:'goals_3', section:'Goals', label:'Anything else we should know about your business?' },
];
